apiVersion: v1
kind: Service
metadata:
  name: nextdns-webhook
  namespace: external-dns
  labels:
    app.kubernetes.io/name: nextdns-webhook
    app.kubernetes.io/component: webhook
spec:
  selector:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/component: nextdns-webhook
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      protocol: TCP
    - name: http-health
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
